### ISSUE TITLE
Page SplashScreen

### ISSUE THREAD

**Issue by dirkzukunft** [dirkzukunft/frotos#11]
## User Story
As a user, when I enter the site at root, I want to see a splash screen site for a moment before I'm getting redirected to the search.

## Design
[Link](https://www.figma.com/file/L4dBE9w4Hc6a6e6PLQiNC9/Perfect-Pic?node-id=2%3A3)

## Acceptance criteria

Feature: Splash Screen Page
  - WhenI am entering the App at /
Then I see a splash screen for 2 seconds
And I'm getting redirected to /search

## Tasks
- [ ] create a page SplashScreen
- [ ] call the page when calling '/'
- [ ] show the SplashScreen component
- [ ] redirect to /search after 2s

## Blocked by
#6 

## Size
S
